### ISSUE TITLE
Incorrect display of compatible_version

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/PluginManager#43] opened 2023-04-09 15:50 UTC
The json states 
> "compatible_version": ">=1.2.20",

but
![image](https://user-images.githubusercontent.com/2079289/230782864-73532a38-55b5-4912-91bf-286b4e55755f.png)

**Comment by aljawaid** [comment] 2023-04-09 20:58
is it picking it up from the plugin.php file I wonder?

**Comment by aljawaid** [comment] 2023-04-09 21:01
once its installed, it should pick up from the plugin.php
`<td class="plugin-compatible-version"><?= $this->text->e($plugin->getCompatibleVersion()) ?></td>` so is your plugin.php correct for ICalConfig?

**Comment by aljawaid** [comment] 2023-04-10 02:02
![image](https://user-images.githubusercontent.com/10233708/230810788-cc425690-d08c-4b18-9c74-4b34774303c1.png)

On mine, once installed, it shows v1.2.20... which is what i have installed... I noticed there is no compatible version in your plugin.php which is why it defaults to the installed version... 1.2.20 for me and 1.2.28 for you

**Comment by aljawaid** [comment] 2023-04-10 02:39
![image](https://user-images.githubusercontent.com/10233708/230814339-9eab06a5-0629-4a66-a56e-043c860e9e0e.png)

Yep, any plugin which has not stated the compatible version defaults to the version of kanboard installed.... this must be a core method

I will close this issue, as it is displaying as intended... feel free to reopen the issue if I have missed anything

**Closed by aljawaid** 2023-04-10 02:39 UTC
Labels: question

**Comment by alfredbuehler** [comment] 2023-04-10 09:33
> I noticed there is no compatible version in your plugin.php which is why it defaults to the installed version... 1.2.20 for me and 1.2.28 for you

My bad. I thought the _plugins.json_ (registry) is the source for that kind of information.
